"""
AI-Powered Diagram Generator Agent
Generates Python diagrams code from architecture using AI
"""
import json
from config.ai_config import config
from utils.ai_client import ai_client


class AIDiagramAgent:
    def __init__(self):
        self.use_ai = config.ai_enabled
    
    def run(self, architecture: dict, cloud_mapping: dict) -> str:
        """
        Generates Python diagrams code from architecture
        
        Args:
            architecture: Architecture specification
            cloud_mapping: Cloud-specific service mapping
            
        Returns:
            Python code using diagrams library
        """
        if self.use_ai:
            return self._generate_with_ai(architecture, cloud_mapping)
        else:
            return self._generate_static(architecture, cloud_mapping)
    
    def _generate_with_ai(self, architecture: dict, cloud_mapping: dict) -> str:
        """Use AI to generate diagrams code"""
        system_prompt = """You are an expert at generating Python code using the 'diagrams' library for AWS/Azure/GCP architecture diagrams.

Generate complete, executable Python code that:
1. Imports necessary components from the diagrams library
2. Creates a professional architecture diagram
3. Uses appropriate cloud provider icons (aws/azure/gcp)
4. Includes clusters for logical grouping
5. Shows data flows with Edge connections
6. Uses proper colors and labels

Return ONLY valid Python code that can be executed directly. No markdown, no explanations, just code.

Use this structure:
```python
from diagrams import Diagram, Cluster, Edge
from diagrams.{provider}.compute import EC2, Lambda
# ... other imports

with Diagram("Architecture Name", show=False, filename="output_architecture"):
    # Create components and clusters
    # Connect with edges
```

Make it production-ready and visually clear."""

        try:
            print("🤖 Using AI to generate diagrams code...")
            
            context = f"""Architecture:
{json.dumps(architecture, indent=2)}

Cloud Mapping ({cloud_mapping['target_cloud']}):
{json.dumps(cloud_mapping, indent=2)}

Generate Python diagrams code for this architecture using {cloud_mapping['target_cloud']} icons."""

            response = ai_client.analyze_with_prompt(system_prompt, context, temperature=0.3)
            
            # Clean response
            response = response.strip()
            if response.startswith("```python"):
                response = response[9:]
            elif response.startswith("```"):
                response = response[3:]
            if response.endswith("```"):
                response = response[:-3]
            response = response.strip()
            
            print("✓ AI diagram code generation complete")
            return response
            
        except Exception as e:
            print(f"⚠️ AI diagram generation failed: {e}")
            print("⚠️ Falling back to static code")
            return self._generate_static(architecture, cloud_mapping)
    
    def _generate_static(self, architecture: dict, cloud_mapping: dict) -> str:
        """Generate static diagram code"""
        cloud = cloud_mapping['target_cloud'].lower()
        
        # Basic template
        code = f'''"""
Auto-generated Architecture Diagram
Generated by Agentic Pre-Sales POC
"""
from diagrams import Diagram, Cluster, Edge

# Import cloud-specific components based on {cloud_mapping['target_cloud']}
'''
        
        if cloud == 'aws':
            code += '''from diagrams.aws.compute import EC2, Lambda, ECS
from diagrams.aws.database import RDS, Dynamodb
from diagrams.aws.network import VPC, ELB
from diagrams.aws.storage import S3
from diagrams.aws.security import KMS, WAF
'''
        elif cloud == 'azure':
            code += '''from diagrams.azure.compute import VM, FunctionApps, ContainerInstances
from diagrams.azure.database import SQLDatabases, CosmosDb
from diagrams.azure.network import VirtualNetworks, LoadBalancers
from diagrams.azure.storage import BlobStorage
from diagrams.azure.security import KeyVaults
'''
        elif cloud == 'gcp':
            code += '''from diagrams.gcp.compute import ComputeEngine, Functions, GKE
from diagrams.gcp.database import SQL, Firestore
from diagrams.gcp.network import VPC, LoadBalancing
from diagrams.gcp.storage import GCS
from diagrams.gcp.security import KMS
'''
        
        code += f'''
def create_architecture():
    with Diagram("Cloud Architecture - {cloud_mapping['target_cloud']}", 
                 show=False, 
                 filename="generated_architecture",
                 direction="TB"):
        
        # Architecture layers from analysis
'''
        
        # Add layers
        for layer in architecture.get('layers', [])[:3]:  # Limit to 3 layers for static
            code += f'''
        with Cluster("{layer['name']}"):
'''
            for component in layer.get('components', [])[:2]:  # Limit components
                safe_name = component.replace(' ', '_').replace('-', '_').lower()
                code += f'            {safe_name} = EC2("{component}")\n'
        
        code += '''
if __name__ == "__main__":
    create_architecture()
    print("✅ Diagram generated: generated_architecture.png")
'''
        
        return code
